// <auto-generated />
namespace Energetic.SqlEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addHistory_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHistory_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "202108040822534_add History_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
