// <auto-generated />
namespace Energetic.SqlEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updtgallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updtgallery));
        
        string IMigrationMetadata.Id
        {
            get { return "202108041349444_updt gallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
